### ISSUE TITLE
Ability to pin import to top of the list

### ISSUE THREAD

**Issue by Nimothy** [neilsoult/typescript-imports-sort#12]
Thank you so much for keeping on the great work of this extension. 
We've run into a slightly interesting issue where we need the ability to pin certain imports to the top of our page. 

For example: `import "reflect-metadata";`, `#!/usr/bin/env node;` or `import "source-map-support/register"`

```typescript
#!/usr/bin/env node;
import "reflect-metadata";
import express, { Application, NextFunction, Request, Response } from "express";
```

However we always have to manually add these back to the top, it would be great if we had a setting that allowed us to "pin" certain imports to the top of the list. 

Thanks in advance,
N

**Comment by Nimothy** [comment]
@neilsoult I started sketching out something for me to use locally: https://github.com/Nimothy/typescript-imports-sort
If you agree with the approach, I can open up a PR.

**Comment by neilsoult** [comment]
@Nimothy sure, I'd be glad to accept a PR for this change.
