### ISSUE TITLE
Orders in pathSortOrderOverride not consistent

### ISSUE THREAD

**Issue by yellowbonV** [neilsoult/typescript-imports-sort#16]
I have to packages needs to be import:
```
import React from 'react';
import { useSelector } from 'react-redux';

import otherCustomComponents from 'absolute paths';
```
is `my settings.json`, here is my settings:
`
"typescript.extension.sortImports.pathSortOrderOverride": [ "react", "react-redux"]
`
With this override `react`, `react-redux` are moved to top after I run `F10`, which is expected.
However, if I run `F10` again the order of `react`, `react-redux` swag, if I run `F10` again, the order swag back. Can we keep the orders consistent without swagging?

Thank you.

**Comment by neilsoult** [comment]
fix released in v1.17.0
