### ISSUE TITLE
pathSortOrder option does not work

### ISSUE THREAD

**Issue by rdeago** [neilsoult/typescript-imports-sort#9]
First of all, thanks and kudos @neilsoult for this great extension! It saved my day after the "death" of TypeScript Hero.

I have set `typescript.extension.sortImports.pathSortOrder` to `["package", "relativeUpLevel", "relativeDownLevel"]` in my workspace settings.  
`typescript.extension.sortImports.sortMethod` is of course set to `"path"`.

My imports are still getting sorted as per the default setting (`["relativeDownLevel", "relativeUpLevel", "package"]`).

Here is the relevant section of `.vscode/settings.json`:

```JSON
      "typescript.extension.sortImports.bracketWhitespace": true,
      "typescript.extension.sortImports.enableJavascript": true,
      "typescript.extension.sortImports.forceTrailingCommas": "multiLineOnly",
      "typescript.extension.sortImports.maxLineLength": 140,
      "typescript.extension.sortImports.maxNamedImportsInSingleLine": 0,
      "typescript.extension.sortImports.multilineIndention": "namesOnly",
      "typescript.extension.sortImports.omitSemicolon": false,
      "typescript.extension.sortImports.pathSortOrder": ["package", "relativeUpLevel", "relativeDownLevel"],
      "typescript.extension.sortImports.quoteStyle": "single",
      "typescript.extension.sortImports.sortMethod": "path",
      "typescript.extension.sortImports.sortOnSave": true
```

Is there any other setting I have to change to make `pathSortOrder` work properly?

Thanks in advance.

**Comment by neilsoult** [comment]
can you provide a minimal repo to reproduce this issue, on maybe stackblitz or codesandbox?

**Comment by rdeago** [comment]
Here's a repro project, maybe not "minimal" but small. I tried to reproduce the conditions I run your extension under (TS path mapping, folder structure).

[path-sort-order-test.zip](https://github.com/neilsoult/typescript-imports-sort/files/6719902/path-sort-order-test.zip)

Repro instructions:
- unzip to a folder of your choice
- In the `path-sort-order-test` subfolder, run `npm install`
- Open the `path-sort-order-test` as a VS Code workspace
- In VS Code, open `src/app/hello/world/say.hello.ts`
- Press Shift+Alt+O (TypeScript's "Organize imports" command) and verify that imports get rearranged: `~base/logging` first, then `../internal/hello`, then `./name`. This (packages > uplevel > downlevel) is the non-configurable order imposed by TypeScript's "Organize imports".
- Press F10 ("Sort imports") or save the file; verify that imports get sorted back to `./name` > `../internal/hello` > `~base/logging`, which is your _default_ path order, but not what is configured in `.vscode/settings.json` (`["package", "relativeUpLevel", "relativeDownLevel"]`).

**Comment by neilsoult** [comment]
Thank you for the repo, this has helped me identify the issue: you are using an import path alias I have not seen or considered. Your alias is prefixed with `~` - this is why the import sorter is not recognizing this as an import string. 

Is this a common prefix for import paths? I have only seen `@` being used, since it is common in npm package names, as well as being recommended by most alias tutorials I have seen online([for example](https://dev.to/larswaechter/path-aliases-with-typescript-in-nodejs-4353)). I can adjust the regex to look for this character, but I am concerned this might not be best practices to use this character in aliasing. Can you provide more insight as to why you chose `~` over `@`?

**Comment by rdeago** [comment]
I use a tilde (`~`) as a prefix to alias application modules and repo-scoped libraries. I chose it because it is the only [URL-safe](https://datatracker.ietf.org/doc/html/rfc3986/#section-2.3) character that sorts after all English letters and decimal digits, both in ASCII and UTF-8. Its spares me name conflicts between path aliases and NPM packages, and I get all alias imports grouped together and placed between external package imports and relative path imports, like this:

```TypeScript
import { John } from '@scoped/package'; // External
import { Paul } from 'another-package'; // External
import { George } from '~app/some-module'; // In repo
import { Ringo } from '~support/library'; // In repo
import { Something } from '../uplevel-module';
import { SomethingElse } from './same-level-module';
import { Foo, Bar } from './subfolder/baz';
```

I too have seen some tutorials recommending `@`. I started using `@` but I didn't like the results:

```TypeScript
import { George } from '@app/some-module'; // In repo
import { John } from '@scoped/package'; // External
import { Ringo } from '@support/library'; // In repo
import { Paul } from 'another-package'; // External
import { Something } from '../uplevel-module';
import { SomethingElse } from './same-level-module';
import { Foo, Bar } from './subfolder/baz';
```

I googled for some established best practice that involves some "special" character other than `@`, but found none, so I came up with my own. Is it common? I don't know, but it sure solves a problem that other people may have. Is it a hack or a forcing? Not at all. As a URL-safe character, I believe the tilde deserves a place in `importRegexString`.

Thanks for the quick reply. I really hope you will find the time to release a version of `typescript-import-sort` that recognizes tildes in import paths.

**Comment by neilsoult** [comment]
tilde is now recognized in 1.13.0

**Comment by rdeago** [comment]
Thanks a lot!
